# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: property.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'property.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eproperty.proto\x12\x08property\"\x1f\n\rParcelRequest\x12\x0e\n\x06parcel\x18\x01 \x01(\t\"4\n\x0f\x41\x64\x64ressResponse\x12\x11\n\taddresses\x18\x01 \x03(\t\x12\x0e\n\x06\x66\x61iled\x18\x02 \x01(\x08\x32W\n\x0ePropertyLookup\x12\x45\n\x0f\x41\x64\x64ressByParcel\x12\x17.property.ParcelRequest\x1a\x19.property.AddressResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'property_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PARCELREQUEST']._serialized_start=28
  _globals['_PARCELREQUEST']._serialized_end=59
  _globals['_ADDRESSRESPONSE']._serialized_start=61
  _globals['_ADDRESSRESPONSE']._serialized_end=113
  _globals['_PROPERTYLOOKUP']._serialized_start=115
  _globals['_PROPERTYLOOKUP']._serialized_end=202
# @@protoc_insertion_point(module_scope)
